version: "3"
services:
    web:
        build: api
        ports:
            - "80:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        # image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Passw0rd"
            ACCEPT_EULA: "Y"